### PR TITLE
Adds AlwaysReturn test helper

### PR DESCRIPTION
**Pull request by poy**

### CODE REVIEW

**Comment by jasonkeene** [comment]
@apoydence You're missing a test case in "given something other than a channel or struct full of channels":

``` go
        It("panics for struct that is not full of channels", func() {
            var invalid struct {
                A <-chan int
                B string
            }
            f := func() {
                testhelpers.AlwaysReturn(invalid, 5, "foo")
            }

            Expect(f).To(Panic())
        })
```

**Comment by nelsam** [comment]
@apoydence: I'm wondering if it'll break with:

``` go
ch := make(chan int64, 100)
testhelpers.AlwaysReturn(ch, 5)
```

My rough guess (without digging in to it) is that `AssignableTo` is not as forgiving as `ConvertibleTo`, and the code would fail without explicitly converting the `5` literal to an `int64`.  Do we want that?

If we _do_, I'd like to see a test a bit more explicitly built around that case.  I think that the `int`->`string` conversion test actually covers that (believe it or not, [`reflect.TypeOf(0).ConvertibleTo(reflect.TypeOf(""))` returns true](http://play.golang.org/p/-p_0yDyvRU)), but the fact that `int64` to `int` conversion isn't supported is a little less clear without a test built around it.

On the other hand, if we _don't_ want that to fail, we should have a test for that and the code should be updated to use `(reflect.Type).ConvertibleTo(typ)` and `(reflect.Value).Convert(typ)`.  We'll need to change the previously-mentioned test to go in the other direction (`string`->`int` fails for the `ConvertibleTo` call), as well.

**Comment by jasonkeene** [comment]
Yeah, it panics without the explicit conversion:

`panic: channel type and argument type have to match`

I think int -> int64 is reasonable but I don't think int -> string is. I'd prefer to have the explicit conversion vs implicit int -> string if we're not going to special case ints.

**Comment by poy** [comment]
So is there an obvious solution? I agree that I would like to be able to do the `int -> int64`. So how do we get the obvious ones, and not the weird ones (`string -> int`)?

**Comment by nelsam** [comment]
To be clear, string->int errors as you'd expect. It's int->string that's a
bit weird.

There is no (sane) way to get one without the other, due to custom named
types (`type foo int64` would be `ConvertibleTo` `type bar string`).
Either we support type conversion or we don't.  There isn't really a way to
straddle the fence, this time.

**Comment by poy** [comment]
Is it just the `string` type?

**Comment by nelsam** [comment]
Come to think of it, maybe we could use the `Kind()` of the value. I'd need
to double check that it works with named types.

And yeah, the only weird one I know of is converting to string - more types
than you'd expect can convert to it through reflection.

**Comment by poy** [comment]
Added the convertible feature and test for Jason.

**Pull request merged**
